name: 'Setup RCPPSW'
description: 'Setup RCPPSW for CI and testing'
inputs:
  cmake_extra_args:  # id of input
    description: 'Extra arguments to pass to cmake'
    required: True
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - name: Install RCPPSW
      shell: bash
      run: |
        echo ${{ inputs.cmake_extra_args }}

        mkdir -p build && cd build
        git clone https://github.com/jharwell/rcppsw.git
        cd rcppsw

        git config --global --add safe.directory $PWD
        git checkout devel
        git submodule update --init --remote --recursive
        mkdir build && cd build

        cmake \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DLIBRA_DEPS_PREFIX=/usr/local \
        -DCMAKE_BUILD_TYPE=DEV \
        -DLIBRA_ER=ALL ${{ inputs.cmake_extra_args }} \
        ..

        JOBS=$(grep -c ^processor /proc/cpuinfo)
        make ticpp
        make -j${JOBS} install
