function(cosm_config_summary )
  message(STATUS "")
  message(STATUS "")
  message(STATUS "COSM Configuration Summary:")
  message(STATUS "")

  message(STATUS "Build environment.....................: COSM_BUILD_ENV=${COSM_BUILD_ENV}")
  message(STATUS "Building for..........................: COSM_BUILD_FOR=${COSM_BUILD_FOR}")
  message(STATUS "Platform..............................: COSM_PAL_TARGET=${COSM_PAL_TARGET}")

  if("${COSM_PAL_TARGET}" MATCHES "ARGOS")
    message(STATUS "Robot type............................: COSM_ARGOS_ROBOT_TYPE=${COSM_ARGOS_ROBOT_TYPE}")
    message(STATUS "Robot name prefix.....................: COSM_ARGOS_ROBOT_NAME_PREFIX=${COSM_ARGOS_ROBOT_NAME_PREFIX}")
    message(STATUS "Robot controller XML ID...............: COSM_ARGOS_CONTROLLER_XML_ID=${COSM_ARGOS_CONTROLLER_XML_ID}")
  elseif("${COSM_PAL_TARGET}" MATCHES "ROS")
    message(STATUS "Robot type............................: COSM_ROS_ROBOT_TYPE=${COSM_ROS_ROBOT_TYPE}")
    message(STATUS "Robot name prefix.....................: COSM_ROS_ROBOT_NAME_PREFIX=${COSM_ROS_ROBOT_NAME_PREFIX}")
    message(STATUS "Custom msg MD5........................: COSM_ROS_MD5=${COSM_ROS_MD5}")
  endif()
endfunction()
