name: ARGoS CI

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "ARGoS CI"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jharwell/ubuntu22.04:2023-04-12
    strategy:
      matrix:
        CMAKE_BUILD_TYPE:
          - OPT
          - DEV
        COSM_BUILD_FOR:
          - ARGOS_FOOTBOT
          - ARGOS_DRONE

    steps:
      - name: Install RCSW
        shell: bash
        run: |
          curl -s --compressed "https://jharwell.github.io/ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ppa.gpg >/dev/null
          sudo curl -s --compressed -o /etc/apt/sources.list.d/ppa.list "https://jharwell.github.io/ppa/ppa.list"
          sudo apt update
          sudo apt-get install rcsw
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rcppsw-setup
        with:
          cmake_extra_args: ''
      - name: Build=${{ matrix.CMAKE_BUILD_TYPE }} HAL_TARGET=${{ matrix.COSM_BUILD_FOR }}
        shell: bash
        run: |

          git config --global --add safe.directory $PWD
          git submodule update --init --remote --recursive
          mkdir -p build && cd build

          cmake  \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DLIBRA_DEPS_PREFIX=/usr/local \
          -DCMAKE_BUILD_TYPE=${{ matrix.CMAKE_BUILD_TYPE }} \
          -DLIBRA_ER=ALL \
          -DCOSM_BUILD_FOR=${{ matrix.COSM_BUILD_FOR }} \
          ..

          make -j$(nproc)
