name: CI & Deploy

on:
  workflow_run:
    workflows:
      - "ARGoS CI"
      - "ROS1 CI"
    types:
      - completed

concurrency:
  group: "CI & Deploy"
  cancel-in-progress: true

jobs:
  ci-argos:
    uses: ./.github/workflows/ci-argos.yml
  ci-ros1:
    uses: ./.github/workflows/ci-ros1.yml

  tag-release:
    runs-on: ubuntu-latest
    needs:
      - ci-argos
      - ci-ros1

    container:
      image: jharwell/ubuntu22.04:2023-04-12
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Push tag
        shell: bash
        run: |
          git config --global --add safe.directory $PWD
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"

          git submodule update --init --remote --recursive

          VERSION_MAJOR=$(sed -nE 's/.*PROJECT_VERSION_MAJOR ([0-9]+).*/\1/p' cmake/project-local.cmake)
          VERSION_MINOR=$(sed -nE 's/.*PROJECT_VERSION_MINOR ([0-9]+).*/\1/p' cmake/project-local.cmake)
          VERSION_PATCH=$(sed -nE 's/.*PROJECT_VERSION_PATCH ([0-9]+).*/\1/p' cmake/project-local.cmake)
          PACKAGE_VERSION=$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH

          if [ "${{ github.ref }}" = "refs/heads/devel" ]; then
            TAG_VERSION=${PACKAGE_VERSION}.beta
            TAG_MESSAGE="Development release ${TAG_VERSION}"
          else
            TAG_VERSION=${PACKAGE_VERSION}
            TAG_MESSAGE="Release ${TAG_VERSION}"
          fi
          git tag ${TAG_VERSION} -m "${TAG_MESSAGE}"
          git push -o ci.skip origin ${TAG_VERSION}
